	title	tddt - Tops monitor (Tenex-DDT).
	subttl	Geoffrey S. Goodfellow/Nov-76.
	comment * This hack is much nicer than the ^Equit shit *
	
	search	monsym

start:	reset				; Reset the world.
	movei	1, 400000		; This fork.
	rpcap
	move	3, 2
	epcap
	movei	1, 100
	cfibf
	movei	1, 100
	movei	2, 15			; Return.
	sti				; Stuff it down tty input.
	jsys	777			; EXEC, take us to the monitor!
	haltf				; The loser ain't a wheel!

	end	start
