!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING ALU
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:ALU.CMD TO-SOURCE:ALU.CMD
COPY FROM-SOURCE:ALU.CTL TO-SOURCE:ALU.CTL
COPY FROM-SOURCE:ALUPRM.MAC TO-SOURCE:ALUPRM.MAC
COPY FROM-SOURCE:ALU.MAC TO-SOURCE:ALU.MAC

;Documentation for product
COPY FROM-SOURCE:ALU.DOC TO-SOURCE:ALU.DOC
COPY FROM-SOURCE:ALUDOC.MEM TO-SOURCE:ALUDOC.MEM

;Final product
COPY FROM-SOURCE:ALU.EXE TO-SOURCE:ALU.EXE
