;
!COMMAND FILE FOR GETTING ALL FILES NEEDED TO ASSEMBLE AND RUN USAG20
;INFORMATION LOGICAL-NAMES
;
;Files required to build product
COPY FROM-SOURCE:USAG20.CBL TO-SOURCE:
COPY FROM-SOURCE:USAG20.CMD TO-SOURCE:
COPY FROM-SOURCE:USAG20.CTL TO-SOURCE:
;
;Documentation for product
COPY FROM-SOURCE:USAG20.TXT TO-SOURCE:
COPY FROM-SOURCE:USAG20.HLP TO-SOURCE:
COPY FROM-SOURCE:USAG20.DOC TO-SOURCE:
;
;Library files used for symbols
;
;Final product
COPY FROM-SOURCE:USAG20.EXE TO-SOURCE:
COPY FROM-SOURCE:USAG20.CHG TO-SOURCE:
COPY FROM-SOURCE:USAG20.LIB TO-SOURCE:
