!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING REV
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:REV.CMD TO-SOURCE:REV.CMD
COPY FROM-SOURCE:REV.CTL TO-SOURCE:REV.CTL
COPY FROM-SOURCE:REV.MAC TO-SOURCE:REV.MAC

;Documentation for product
COPY FROM-SOURCE:REV.HLP TO-SOURCE:REV.HLP

;Final product
COPY FROM-SOURCE:REV.EXE TO-SOURCE:REV.EXE
