!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING REDIT
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:REDIT.CMD TO-SOURCE:REDIT.CMD
COPY FROM-SOURCE:REDIT.CTL TO-SOURCE:REDIT.CTL
COPY FROM-SOURCE:REDIT.MAC TO-SOURCE:REDIT.MAC

;Documentation for product
COPY FROM-SOURCE:REDIT.DOC TO-SOURCE:REDIT.DOC
COPY FROM-SOURCE:REDIT.MEM TO-SOURCE:REDIT.MEM

;Final product
COPY FROM-SOURCE:REDIT.EXE TO-SOURCE:REDIT.EXE
