@DEFINE REL: SYS:
@COMPILE DAPSYM.MAC,DAPLIB,NFT,FAL,DNCONN
@LOAD %"SET:DATA:150000/LOCALS/SYMSEG:PSECT:.LOW./SAVE" NFT,DAPLIB,DNCONN
@LOAD %"SET:DATA:150000/LOCALS/SYMSEG:PSECT:.LOW./SAVE" FAL,DAPLIB
