!NFTFAL.CTL
!
!                     COPYRIGHT (c) 1985 BY
!	      DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
!
! THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
! ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
! INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
! COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
! OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
! TRANSFERRED.
!
! THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
! AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
! CORPORATION.
!
! DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS
! SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
!

!
!This Control File Assembles, Loads, and saves NFT and FAL
!
!To use this file, ensure that the required files are in the
!proper area and then:
!
!	SUBMIT NFTFAL/TIME:0:30:00

!Required universal files on SYS:

!	MONSYM.UNV		Monitor symbol definitions
!	MACSYM.UNV		Monitor macro definitions
!	GLXMAC.UNV		Galaxy macro definitions
!	QSRMAC.UNV		Quasar symbol definitions

!Required object files

!	SYS:GLXINI.REL		Galaxy library bootstrap  Galaxy V4
!	REL:GLXLIB.REL		Galaxy library		  Galaxy V4.2

!Source Files

!	DAPSYM.MAC		DAP symbol definitions
!	DAPLIB.MAC		Common routines for FAL and NFT
!	NFT.MAC			NFT source module
!	FAL.MAC			FAL source module
!	DNCONN.MAC		Poor man' routing source module

!Object Files created (deleted on successful completion)

!	DAPSYM.UNV
!	DAPSYM.REL
!	DAPLIB.REL
!	NFT.REL
!	FAL.REL
!	DNCONN.REL

!Executable Files 

!	NFT.EXE
!	FAL.EXE

!Documetation Files

!	NFT.HLP

!Don't generate listings unless requested
@DEFINE LPT: NUL:
@DEFINE REL: DSK:,SYS:
!@DEFINE SYS: DSK:,SYS:
DOCREF::

@ENABLE
!Show logical names
@INFO LOGICAL

!Do directory of all source files
@VDIRECT DAPSYM.MAC,DAPLIB.MAC,FAL.MAC,NFT.MAC,DNCONN.MAC,
@CHECK SEQ
@

!Do directory of all required files
@VDIR SYS:MONSYM.UNV,
@CHECK SEQ
@
@VDIR SYS:MACSYM.UNV,
@CHECK SEQ
@
@VDIR SYS:GLXMAC.UNV,
@CHECK SEQ
@
@VDIR SYS:QSRMAC.UNV,
@CHECK SEQ
@
@VDIR SYS:GLXINI.REL,
@CHECK SEQ
@
@VDIR REL:GLXLIB.REL,
@CHECK SEQ
@

!--DAPLIB
@COMPILE/COMP/CREF DAPSYM.MAC
@MACRO
*DAPLIB.REL,DAPLIB.CRF/C/P/P=DAPLIB.MAC
*^C

!--NFT
@COMPILE/COMP/CREF NFT.MAC

!--FAL
@COMPILE/COMP/CREF FAL.MAC

!--DNCONN
@COMPILE/COMP/CREF DNCONN.MAC

LOAD::

!Get a copy of GLXINI.REL from SYS:   (Galaxy 4)
@COPY SYS:GLXINI.REL (TO) DSK:
!Get a copy of GLXLIB.REL from REL:   (Galaxy 4.2)
@COPY REL:GLXLIB.REL (TO) DSK:

@LOAD %"SET:DATA:150000/LOCALS/SYMSEG:PSECT:.LOW./SAVE" NFT,DAPLIB,DNCONN
@GET NFT
@INFORMATION VERSION

@LOAD %"SET:DATA:150000/LOCALS/SYMSEG:PSECT:.LOW./SAVE" FAL,DAPLIB
@GET FAL
@INFORMATION VERSION

@VDIRECT DAPSYM.UNV,DAPLIB.REL,DNCONN.REL,FAL.REL,NFT.REL,FAL.EXE,NFT.EXE,
@CHECK SEQ
@

!Generate CREFS
@CREF
@IF (ERROR) !OKAY - PROBABLY NOT WANTED ANYWAY
@CREF
*LPT:=DAPLIB.CRF
*^C

!Delete unwanted files
@DELETE DAPSYM.UNV,DAPSYM.REL,DAPLIB.REL,NFT.REL,FAL.REL,GLXINI.REL,GLXLIB.REL,DNCONN.REL

FINI::
@PLEASE	NFT and FAL Assembly Successful
%CERR::
%ERR::
@PLEASE	Error During NFT or FAL Assembly
%FIN::
