!Command file for obtaining all files relevant to building NFT & FAL

!Files required to build product

COPY FROM-SOURCE:DAPLIB.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DAPSYM.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DNCONN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:FAL.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NFT.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NFTFAL.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:NFTFAL.CMD TO-SOURCE:*.*.-1


!Documentation for product

COPY FROM-DOC:NFT.HLP TO-DOC:*.*.-1


!Final product

COPY FROM-SUBSYS:NFT.EXE TO-SUBSYS:*.*.-1
COPY FROM-SUBSYS:FAL.EXE TO-SUBSYS:*.*.-1
