!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING SETHOST
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:SETHOS.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETHOS.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETHOS.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:SETHOST.EXE TO-SUBSYS:*.*.-1
