!	Job to test the FORTRAN system on the DECSYSTEM-20
!	SUBMIT F20TST.CTL /TIME:0:05:00

!COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1981, 1987
!ALL RIGHTS RESERVED.
!
!THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
!ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH LICENSE AND WITH THE
!INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR ANY  OTHER
!COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
!OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE  SOFTWARE  IS  HEREBY
!TRANSFERRED.
!
!THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT  NOTICE
!AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
!CORPORATION.
!
!DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY  OF  ITS
!SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.

!	VERSION 11	  F20TST.CTL	May 1986

! Control file to run the FORTRAN version 11 installation test system and
! confirm that all essential parts of Fortran are present on release tapes.

! Files needed on DSK:
!	F20TST.CTL	This file

!	FORTRA.EXE
!	FORTRA.HLP
!	FORLIB.REL
!	FORO11.EXE
!	FORDDT.HLP
!	FORDDT.REL
!	FORPRM.UNV
!	LINK.EXE
!	OVRLAY.REL

!	ARRAYS.FOR
!	ASCII.FOR
! 	BINARY.FOR
!	CHARIO.FOR
!	CHFUN.FOR
!	COMEQ.FOR
!	DO.FOR
!	DOWHIL.FOR
!	GOTO.FOR
!	IF.FOR
!	IFTHEL.FOR
!	IMAGE.FOR
!	INTFIL.FOR
!	IOEXPR.FOR
!	LIB.FOR
!	LONG.FOR
!	NAMLST.DAT
!	NAMLST.FOR
!	OVL0.FOR
!	OVL1.FOR
!	OVL2.FOR
!	OVL3.FOR
!	OVL4.FOR
!	OVL5.FOR
!	OVL6.FOR
!	RANDOM.FOR
!	RMSIO.FOR
!	FNDRMS.MAC
!	SUBFUN.FOR
!	SUBSTR.FOR
!	T4DDT.FOR
!	V7DO.FOR
!	V7LIB.FOR

!	The following files are quired on DSK:, and are included
!	in the PS:<FORTRAN-OTS-DEBUGGER> saveset:

!	RMSINJ.UNV
!	RTLZNM.REL
!	DYNBOO.REL
!	ZERBOO.REL
!	RMSZER.REL

!	Setup libraries.

!***********************************************************************
! DSK: must be defined to find the sources for testing
!***********************************************************************
!@DEFINE DSK:
@DEFINE SYS: DSK:,SYS:
@DEFINE HLP: DSK:

!	Clean out.

@NOERROR
@DELETE ARRAYS.REL,ASCII.LST,ASCII.REL,BINARY.REL,DO.REL,GOTO.REL,
@EXPUNGE
@
@DELETE IF.REL,IMAGE.REL,LIB.REL,RANDOM.REL,SUBFUN.REL,T4DDT.REL,
@EXPUNGE
@
@DELETE CHARIO.REL,CHDATA.REL,CHFUN.REL,COMEQ.REL,RMSIO.REL,FNDRMS.REL,
@EXPUNGE
@
@DELETE IFTHEL.REL,INTFIL.REL,IOEXPR.REL,NAMLST.REL,DOWHIL.REL,
@EXPUNGE
@
@DELETE OVL0.REL,OVL1.REL,OVL2.REL,OVL3.REL,OVL4.REL,OVL5.REL,OVL6.REL,
@EXPUNGE
@
@DELETE SUBSTR.REL,V7DO.REL,V7LIB.REL,LONG.REL,
@EXPUNGE
@
@DELETE FOR20.DAT,FOR21.DAT,FOR22.DAT,FOR23.DAT,
@EXPUNGE
@
@ERROR

!	Check for all required FORTRAN components.

@ERROR %
@DIRECT DSK:FORTRA.EXE, DSK:FORTRA.HLP, DSK:FORLIB.REL, DSK:FORO11.EXE
@IF (ERROR) @GOTO UERR
@DIRECT DSK:FORDDT.HLP, DSK:FORDDT.REL
@IF (ERROR) @GOTO UERR
@ERROR

@GET DSK:FORTRA.EXE
@INFORMATION VERSION

@GET DSK:FORO11.EXE
@INFORMATION VERSION

@GET DSK:LINK.EXE
@INFORMATION VERSION


!	Warnings are not permitted either.
@ERROR %


!	Generate a binary (.REL) and listing (.LST) file and verify that
!	they were produced.  Also check the compiler HELP facility.

@FORTRA
*ASCII,ASCII=ASCII.FOR
@IF (ERROR) @GOTO UERR
*/HELP
@IF (ERROR) @GOTO UERR


@DIRECT ASCII.LST
@IF (ERROR) @GOTO UERR
@DIRECT ASCII.REL
@IF (ERROR) @GOTO UERR


!	Test to see  that all intrinsic  functions and Fortran  supplied
!	subroutines exist in FORLIB. If  LINK produces an error such  as
!	"Undefined Globals",  then some  of  the routines  are  missing.
!	Program is merely loaded, not executed.

@COMPILE LIB.FOR
@LOAD LIB.REL
@IF (ERROR) @GOTO UERR


!	Run FORDDT & make sure it works minimally.
!	No errors of any type should appear.

@DEBUG T4DDT.FOR /LANGUAGE-SWITCH:"/DEBUG:ALL"
;V10 does not prompt for the name of the program
;*T4DDT
*HELP
*PAUSE 10
*START
*TYPE X
*MODE I
*TYPE I
*STOP
@IF (ERROR) @GOTO UERR


!	Test non-sharable FOROTS.
!	ASCII previously compiled.

@LINK
*ASCII.REL /OTS:NONSHAR /GO
@START
@IF (ERROR) @GOTO UERR


!	Try FORDDT with the non-sharable FOROTS.

@COMPILE T4DDT.FOR /COMP /LANGUAGE-SWITCH:"/DEB:(DIM,BOU)"
@LINK
*T4DDT.REL /SEG:LOW /DEBUG:FORTRA /OTS:NONSHAR /GO
;*V10 doesn't need the main program's needed
;*T4DDT
*PAUSE 10
*START
*TYPE X
*CONTINUE
@IF (ERROR) @GOTO UERR


!	Test arrays.
 
@EXECUTE ARRAYS.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE ARRAYS.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test ASCII I/O.
 
@EXECUTE ASCII.FOR /COMP
@IF (ERROR) @GOTO UERR
@EXECUTE ASCII.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test BINARY I/O.
 
@EXECUTE BINARY.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE BINARY.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test DO loops.
 
@EXECUTE DO.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE DO.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test GO TO statements.

@EXECUTE GOTO.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE GOTO.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test IF statements.
 
@EXECUTE IF.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE IF.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test IMAGE I/O.
 
@EXECUTE IMAGE.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE IMAGE.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test RANDOM access I/O.
 
@EXECUTE RANDOM.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE RANDOM.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR
 
 
!	Test subroutines and functions.
 
@EXECUTE SUBFUN.FOR
@IF (ERROR) @GOTO UERR
@EXECUTE SUBFUN.FOR /COMP /OPT
@IF (ERROR) @GOTO UERR

!	Character I/O

EXECUTE CHARIO.FOR
@IF (ERROR) @GOTO UERR

!	Character data in DATA statements

@EXECUTE CHDATA.FOR
@IF (ERROR) @GOTO UERR

!	Character Functions

@EXECUTE CHFUN.FOR
@IF (ERROR) @GOTO UERR

!	Character COMMON/EQUIVALENCE

@EXECUTE COMEQ.FOR
@IF (ERROR) @GOTO UERR

!	DO WHILE

@EXECUTE DOWHIL.FOR
@IF (ERROR) @GOTO UERR

!	IF-THEN-ELSE

@EXECUTE IFTHEL.FOR
@IF (ERROR) @GOTO UERR

!	Internal files

@EXECUTE INTFIL.FOR
@IF (ERROR) @GOTO UERR

!	Expression in I/O statements

@EXECUTE IOEXPR.FOR
@IF (ERROR) @GOTO UERR

!	NAMELIST I/O

@EXECUTE NAMLST.FOR
@IF (ERROR) @GOTO UERR

!	Overlays

@COMPILE /COMP OVL0.FOR,OVL1.FOR,OVL2.FOR,OVL3.FOR,OVL4.FOR,OVL5.FOR,OVL6.FOR
@IF (ERROR) @GOTO UERR

@LINK
@IF (ERROR) @GOTO UERR
*TEST/OVERLAY
@IF (ERROR) @GOTO UERR
*tty:/plot
@IF (ERROR) @GOTO UERR
*/ERROR:0
@IF (ERROR) @GOTO UERR
*OVL0,OVL1/LINK:TEST
@IF (ERROR) @GOTO UERR
*	/NODE:TEST OVL2/LINK:LEFT
@IF (ERROR) @GOTO UERR
*		/NODE:LEFT OVL5/LINK:LEFT1
@IF (ERROR) @GOTO UERR
*		/NODE:LEFT OVL6/LINK:LEFT2
@IF (ERROR) @GOTO UERR
*	/NODE:TEST OVL3,OVL4/LINK:RIGHT
@IF (ERROR) @GOTO UERR
*TEST/SAVE
@IF (ERROR) @GOTO UERR
*/E/G
@IF (ERROR) @GOTO UERR

!	Character substring

@EXECUTE SUBSTR.FOR
@IF (ERROR) @GOTO UERR

!	Zero-trip DO loops

@EXECUTE V7DO.FOR
@IF (ERROR) @GOTO UERR

@EXECUTE V7DO.FOR/COMP/OPT
@IF (ERROR) @GOTO UERR

!	ANSII-77 library routines.  Something is wrong if LINK cannot
!	find them.

@LOAD V7LIB.FOR
@IF (ERROR) @GOTO UERR

!	VMS Long symbols

@EXECUTE LONG.FOR /COMPILE/FORTRAN
@IF (ERROR) @GOTO UERR

@EXECUTE LONG.FOR /COMPILE/FORTRAN/OPT
@IF (ERROR) @GOTO UERR

!	RMS I/O test

@EXECUTE RMSIO.FOR/FORTRAN/COMPILE,FNDRMS.MAC /COMPILE
@IF (ERROR) @GOTO UERR

@EXECUTE RMSIO.FOR/FORTRAN/OPT/COMPILE,FNDRMS.MAC /COMPILE
@IF (ERROR) @GOTO UERR

@GOTO END




%ERR::
@GOTO UERR

UERR::
!	*********************************************************
!	*********************************************************	
!	*							*
!	*	?Unexpected error - should not occur		*
!	*							*
!	*********************************************************
!	*********************************************************
@GOTO END

END::
!	Cleanup
@
@NOERROR
@DELETE ARRAYS.REL,ASCII.LST,ASCII.REL,BINARY.REL,DO.REL,GOTO.REL,
@EXPUNGE
@
@DELETE IF.REL,IMAGE.REL,LIB.REL,RANDOM.REL,SUBFUN.REL,T4DDT.REL,
@EXPUNGE
@
@DELETE CHARIO.REL,CHDATA.REL,CHFUN.REL,COMEQ.REL,RMSIO.REL,LONG.REL,
@EXPUNGE
@
@DELETE IFTHEL.REL,INTFIL.REL,IOEXPR.REL,NAMLST.REL,
@EXPUNGE
@
@DELETE OVL0.REL,OVL1.REL,OVL2.REL,OVL3.REL,OVL4.REL,OVL5.REL,OVL6.REL,
@EXPUNGE
@
@DELETE SUBSTR.REL,V7DO.REL,V7LIB.REL,DOWHIL.REL,
@EXPUNGE
@
@DELETE FOR20.DAT,FOR21.DAT,FOR22.DAT,FOR23.DAT,
@EXPUNGE
@
@ERROR

%FIN::

!	[End F20TST.CTL]
