	SUBROUTINE OVL2A(ARG)

C COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1982, 1987
C ALL RIGHTS RESERVED.
C 
C THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
C ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH LICENSE AND WITH THE
C INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR ANY  OTHER
C COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
C OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE  SOFTWARE  IS  HEREBY
C TRANSFERRED.
C 
C THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT  NOTICE
C AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
C CORPORATION.
C 
C DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY  OF  ITS
C SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.

	IMPLICIT DOUBLE PRECISION (D)
	IMPLICIT COMPLEX (C)
	IMPLICIT INTEGER (A)
	INTEGER OVL6

	TYPE 1
1	FORMAT (1X,'	OVL2A CALLS OVL5'/)
	ARG=0
	CALL OVL5(ARG)
	TYPE 2
2	FORMAT (1X,'	RETURN TO OVL2A'/)
	IF (ARG.NE.1) TYPE 100
100	FORMAT(' ?Error. Value not returned from OVL5')

	TYPE 3
3	FORMAT (1X,'	OVL2A CALLS OVL6'/)
	NUM=0
	NUM=OVL6(NUM)
	TYPE 2
	IF (NUM.NE.1) TYPE 300
300	FORMAT(' ?Error. Value not returned from OVL6')

	ARG=1		!Return value
	RETURN
	END

	SUBROUTINE OVL2B

	IMPLICIT DOUBLE PRECISION (D)
	IMPLICIT COMPLEX (C)
	IMPLICIT INTEGER (A)

	TYPE 1
1	FORMAT (/1X,'		OVL2B DOESN''T CALL ANYTHING')

	RETURN
	END
