	INTEGER FUNCTION OVL6(ARG)

C COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1982, 1987
C ALL RIGHTS RESERVED.
C 
C THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED
C ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH LICENSE AND WITH THE
C INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR ANY  OTHER
C COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
C OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE  SOFTWARE  IS  HEREBY
C TRANSFERRED.
C 
C THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT  NOTICE
C AND  SHOULD  NOT  BE  CONSTRUED  AS A COMMITMENT BY DIGITAL EQUIPMENT
C CORPORATION.
C 
C DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY  OF  ITS
C SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.

	IMPLICIT DOUBLE PRECISION (D)
	IMPLICIT COMPLEX (C)
	IMPLICIT INTEGER (A)

	TYPE 1
1	FORMAT (30x,'	OVL6 CALLS OVL2B'/)
	NUM=0
	CALL OVL2B(NUM)
	TYPE 2
2	FORMAT (30x,'	RETURN TO OVL6'/)
	IF (NUM .NE. 0) TYPE 100
100	FORMAT(' ?Error. Value not returned from OVL2A')

	OVL6=1
	RETURN
	END
