/* Routine to produce a byte pointer suitable for memmove().
 * It assumes that only pointers generated by KCC can be presented
 * (e.g., 6, 7, 8, 9, or 18 bit byte pointers, or a memory address).
 *
 * If it is a memory address, just make it point to the first 9 bit
 * byte in that location.
 *
 * If it is already a byte pointer, use different runtime code for the
 * extended and non-extended cases to:
 *	Test for 18 bit byte pointer, if not, just return.
 *	Otherwise, convert to a 9 bit pointer to the correct halfword.
 */
char *_chptr(p)
int p;
{
#asm
	MOVE 1,-1(17)
	JUMPGE 17,CHPTX		/* Jump if extended */
	TLNN 1,777700		/* Is it a byte pointer? */
	 TLOA 1,331100		/* No, make it 9 bit, first byte */
	TLNN 1,006000		/* Is it 18 bit pointer? */
	 POPJ 17,		/* No, all done */
	TLZE 1,770000		/* Left or right half? */
	 TLO 1,220000		/* Left, keep it there */
	TLC 1,113300		/* Point to first 9 bit byte of left */
				/* or right half */
	POPJ 17,

CHPTX:	TLNN 1,770000		/* Is it a byte pointer? */
	 TLO 1,700000		/* No, make it 9 bit, first byte */
	TLC 1,740000
	TLCN 1,740000		/* 18 bit pointer? */
	 TLZ 1,050000		/* Yes, convert to 9 bit */
#endasm
}
