!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING MAIL
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:MAIL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAIL.CTL TO-SOURCE:*.*.-1
;COPY FROM-SOURCE:REL1.MAC TO-SOURCE:*.*.-1
;COPY FROM-SOURCE:CMD.MAC TO-SOURCE:*.*.-1
;COPY FROM-SOURCE:CMD.REL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAIL.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:MAIL.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:MAIL.DOC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:MAIL.EXE TO-SOURCE:*.*.-1
