!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING TYPVFU
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:TYPVFU.CMD TO-SOURCE:TYPVFU.CMD
COPY FROM-SOURCE:TYPVFU.CTL TO-SOURCE:TYPVFU.CTL
COPY FROM-SOURCE:TYPVFU.MAC TO-SOURCE:TYPVFU.MAC

;Final product
COPY FROM-SOURCE:TYPVFU.EXE TO-SOURCE:TYPVFU.EXE
