;
!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING IPHOST
;INFORMATION LOGICAL-NAMES FROM-*:
;INFORMATION LOGICAL-NAMES TO-*:
;
;Files required to build product iphost
COPY FROM-source:IPHOST.CMD TO-SOURCE:
COPY FROM-source:IPHOST.CTL TO-SOURCE:
COPY FROM-SOURCE:IPHOST.HLP TO-SOURCE:
COPY FROM-ARPA:IPHOST.MAC TO-SOURCE:
;
;Final product
COPY FROM-ARPA:IPHOST.EXE TO-SUBSYS:

