;Command file to build SYSDPY
INFORMATION LOGICAL-NAMES FROM-*:
INFORMATION LOGICAL-NAMES TO-*:

;Files required to build product
COPY FROM-SOURCE:SYSDPY.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSDPY.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SYSDPY.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DPY.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DPYDEF.MAC TO-SOURCE:*.*.-1
!COPY FROM-SOURCE:ANADPY.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:SYSDPY.MEM TO-SOURCE:*.*.-1
COPY FROM-hlp:SYSDPY.HLP TO-hlp:*.*.-1
COPY FROM-SOURCE:SYSDPY.DOC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SUBSYS:SYSDPY.EXE TO-SUBSYS:*.*.-1

