;[SU-SIERRA.ARPA]PS:<FTP>FTPPRO.MAC.9, 30-May-86 13:56:14, Edit by GROSSMAN
;Make TCP be preferred over PUP.
;<FTP>FTPPRO.MAC.7,  9-Sep-85 16:36:38, Edit by LOUGHEED
; Merge MIT changes
;[MIT-XX]PS:<GZ.FTP>FTPPRO.MAC.9, 31-Aug-85 15:10:25, Edit by GZ
;(CHASW) Support for chaos ftp.  Had to make PRTDSP and PROTS separate tables.


	SEARCH FTPDEF
	TTITLE(FTPPRO, -- Definitions for protocols known by FTP)
	SUBTTL David Eppstein / Stanford University  19-Oct-83

	;; This is in a separate module from FTP.MAC so that
	;; new protocols may be defined without having to change
	;; the user interface routines that call the protocols.
	;;
	;; Copyright (C) 1984, 1985 Board of Trustees, Stanford University
	;; The information in this software is subject to change without
	;; notice and should not be construed as a commitment by Stanford
	;; University.  Stanford assumes no responsibility for the use or
	;; reliability of this software.

DEFINE PROT (NAM,VEC,MOD) <	;;Macro to define protocol vector entry
	.REQUIRE MOD		;;Make module for that protocol get loaded
	EXTN VEC		;;Make sure vector is defined
	[ASCIZ/NAM/],,VEC	;;Make actual HSTNAM table entry
>

	EXTERN HSTSTR

; Table of protocols implemented
; PRTDSP is alphabetical, PROTS is in order of preference

PRTDSP::TABLE
IFN CHASW,<
	PROT(Chaos,CFTVEC,CHAFTP)	;Chaos FTP (not FILE)
>
IFN PUPSW,<
	PROT(Pup,PUPVEC,PUPFTP)
>
	PROT(TCP,TCPVEC,TCPFTP)
	TEND
	0

PROTS::	TABLE
	PROT(TCP,TCPVEC,TCPFTP)
IFN PUPSW,<
	PROT(Pup,PUPVEC,PUPFTP)
>
IFN CHASW,<
	PROT(Chaos,CFTVEC,CHAFTP)	;Chaos FTP (not FILE)
>
	TEND
	0


; Vector for unimplemented protocols
; keep this for easy patching even if currently all protocols are implemented.

NYIVEC:	R			; .CLOSE does nothing (never called)
	NYIOPN			; .OPEN complains that protocol unimplemented
	REPEAT <VECSIZ-2>,<R>	; Everything else does nothing (never called)

CHKVEC NYIVEC			; Make sure vector is the right length

NYIOPN:	HLRO A,V		; Copy string pointer to protocol name
	HRROI B,HSTSTR		; Point to host name to
	TYPE <Cannot connect to %1S host %2S - protocol unimplemented%/>
	RET

	END
