!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO KRYPTN
INFORMATION LOGICAL-NAMES FROM-*:
INFORMATION LOGICAL-NAMES TO-*:

;Files required to build product
COPY FROM-SOURCE:KRYPTN.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:KRYPTN.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:KRYPTN.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:KRYPTN.EXE TO-SUBSYS:*.*.-1

