!* -*- teco -*- *!
!* sample init file for stand alone babyl.exe!

2uEcho Area Height		    !* see more of msg!
1uError Messages In Echo Area	    !* why not?!
66uFill Column		    !* no wrap around on our msgs!
1m.vAuto Fill Mode		    !* do it automagically!

!* BABYL variables for mail reading!

:I*David ChapmanM.VBabyl Personal Namew
5M.VBabyl FROM/TO Controlw
1M.VBabyl Day of Week Flagw
1M.VBabyl F Controlw
1M.VBabyl Require Subjectsw
:I*MM & Babyl R Done HookM.VBabyl R Done Hook
:I*MM & Babyl O Done HookM.VBabyl O Done Hook

:I* MM ^R Babyl Add Cc-Recipient !* ask for CC:'s!
    m.m^R Babyl Yank[...Y	    !* need this cruft b/c we have hook!
    1,m.m^R Fill Indented Mail Region[...\
    qParagraph Delimiteru2
    fq2"g :i22-'"# :i2-'
    q2[Paragraph DelimiterM.VBabyl Edit Mail Hook

