!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO CISTS
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:CISTS.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CISTS.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:CISTS.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:CISTS.EXE TO-SUBSYS:*.*.-1

