COPY FROM-SOURCE:KCNO10.REL TO-SOURCE:*.*
COPY FROM-SOURCE:KCSUB.REL TO-SOURCE:*.*
COPY FROM-SOURCE:KCUNV.UNV TO-SOURCE:*.*
COPY FROM-SOURCE:RELOC.KCM TO-SOURCE:*.*
COPY FROM-SOURCE:STOR.KCM TO-SOURCE:*.*

COPY FROM-SOURCE:RMTCNM.MAC TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCNM.REL TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCNP.MAC TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCNP.REL TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCNT.MAC TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCNT.REL TO-SOURCE:*.*

COPY FROM-SOURCE:RMTCND.TXT TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.CMD TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.CTL TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.DOC TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.EXE TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.HLP TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.MAP TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.RNO TO-SOURCE:*.*
COPY FROM-SOURCE:RMTCON.SEQ TO-SOURCE:*.*


