;Command file to copy all needed files for building TTYINI.

;Source files
COPY FROM-SOURCE:TTYINI.CTL TO-SOURCE:
COPY FROM-SOURCE:TTYINI.MAC TO-SOURCE:
COPY FROM-SOURCE:TTYINI.CMD TO-SOURCE:

;Final product
COPY FROM-SOURCE:TTYINI.EXE TO-SUBSYS:
