;;; DSYMS2.MAC -- tidy up a DSYMS file.  See DSYMS1.MAC.
;;;
;;; Copyright (c) 1987 Massachusetts Institute of Technology.
;;;
;;; Note that there is absolutely NO WARRANTY on this software.
;;; See the file COPYRIGHT.NOTICE for details and restrictions.

; Constant stuff
	PURGE	BCONST,DCONST,OCONST,ECONST

; Structure stuff
	PURGE	BSTRUCT,DFIELD,DHALF,DFILL,DWORD,DWORDS,ESTRUCT

; Tuple stuff
	PURGE	BTUPLE,TUPLE,ATUPLE,ETUPLE

; RDATA stuff
	PURGE	BRDATA,RDATA,ARDATA,ERDATA

; Internal symbols
	PURGE	$$$CVT,$$$EQV
	IFDEF	$$$WRD,<PURGE $$$WRD>
	IFDEF	$$$FLD,<PURGE $$$FLD>

	END
