!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO DNSNUP

INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:DNSNUP.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DNSNUP.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DNSNUP.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:DNSNUP.HLP TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:DNSNUP.EXE TO-SUBSYS:*.*.-1
