!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO DNTATL

INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:DNTATL.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DNTATL.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:DNTATL.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:DNTATL.HLP TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:DNTATL.EXE TO-SUBSYS:*.*.-1
