COPY FROM-SOURCE:HOST.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HSDNCN.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HOST.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:HOST.CMD TO-SOURCE:*.*.-1

COPY FROM-SOURCE:HOST.EXE TO-SUBSYS:*.*.-1
