!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO SETNOD

INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:SETNOD.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETNOD.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SETNOD.MAC TO-SOURCE:*.*.-1

;Documentation for product

;Final product
COPY FROM-SOURCE:SETNOD.EXE TO-SUBSYS:*.*.-1
