!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO SCM
INFORMATION LOGICAL-NAMES FROM-*:
INFORMATION LOGICAL-NAMES TO-*:

;Files required to build product
COPY FROM-SOURCE:SCM.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCM.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCM.MAC TO-SOURCE:*.*.-1

;Final product
COPY FROM-SOURCE:SCM.HLP TO-SOURCE:*.*.-1
COPY FROM-SOURCE:SCM.EXE TO-SUBSYS:*.*.-1

