!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING QUETST
INFORMATION LOGICAL-NAMES FROM*:
INFORMATION LOGICAL-NAMES TO*:

;Files required to build product
COPY FROM-SOURCE:QUETST.CMD TO-SOURCE:QUETST.CMD
COPY FROM-SOURCE:QUETST.CTL TO-SOURCE:QUETST.CTL
COPY FROM-SOURCE:QUETST.MAC TO-SOURCE:QUETST.MAC

;Documentation for product
COPY FROM-SOURCE:QUETST.DOC TO-SOURCE:QUETST.DOC

;Final product
COPY FROM-SOURCE:QUETST.EXE TO-SOURCE:QUETST.EXE
